# -*- coding: utf-8 -*-
"""TOPSIS_Assignment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mubow2XGss2ditivEb0hQcfzNITfLqv7

# **TOPSIS Implementation in Python (Command Line Program)**

This notebook creates a Python command-line program to implement  
TOPSIS (Technique for Order Preference by Similarity to Ideal Solution).

Steps covered:
1. Reading input CSV file
2. Validating inputs
3. Applying TOPSIS algorithm
4. Generating output CSV with score and rank

# **Creating topsis.py file**
"""

# Commented out IPython magic to ensure Python compatibility.
# %%writefile topsis.py
# import sys
# import pandas as pd
# import numpy as np
# 
# def topsis(input_file, weights, impacts, output_file):
#     try:
#         data = pd.read_csv(input_file)
#     except FileNotFoundError:
#         print("Error: Input file not found.")
#         sys.exit(1)
# 
#     if data.shape[1] < 3:
#         print("Error: Input file must have at least 3 columns.")
#         sys.exit(1)
# 
#     criteria_data = data.iloc[:, 1:]
# 
#     if not np.all(criteria_data.applymap(np.isreal)):
#         print("Error: All criteria values must be numeric.")
#         sys.exit(1)
# 
#     weights = weights.split(',')
#     impacts = impacts.split(',')
# 
#     if len(weights) != criteria_data.shape[1]:
#         print("Error: Number of weights must match number of criteria.")
#         sys.exit(1)
# 
#     if len(impacts) != criteria_data.shape[1]:
#         print("Error: Number of impacts must match number of criteria.")
#         sys.exit(1)
# 
#     for impact in impacts:
#         if impact not in ['+', '-']:
#             print("Error: Impacts must be '+' or '-'.")
#             sys.exit(1)
# 
#     weights = np.array(weights, dtype=float)
# 
#     norm_matrix = criteria_data / np.sqrt((criteria_data ** 2).sum())
#     weighted_matrix = norm_matrix * weights
# 
#     ideal_best = []
#     ideal_worst = []
# 
#     for i in range(len(impacts)):
#         if impacts[i] == '+':
#             ideal_best.append(weighted_matrix.iloc[:, i].max())
#             ideal_worst.append(weighted_matrix.iloc[:, i].min())
#         else:
#             ideal_best.append(weighted_matrix.iloc[:, i].min())
#             ideal_worst.append(weighted_matrix.iloc[:, i].max())
# 
#     ideal_best = np.array(ideal_best)
#     ideal_worst = np.array(ideal_worst)
# 
#     dist_best = np.sqrt(((weighted_matrix - ideal_best) ** 2).sum(axis=1))
#     dist_worst = np.sqrt(((weighted_matrix - ideal_worst) ** 2).sum(axis=1))
# 
#     topsis_score = dist_worst / (dist_best + dist_worst)
# 
#     data['Topsis Score'] = topsis_score
#     data['Rank'] = data['Topsis Score'].rank(ascending=False).astype(int)
# 
#     data.to_csv(output_file, index=False)
#     print("TOPSIS analysis completed successfully.")
# 
# 
# if __name__ == "__main__":
#     if len(sys.argv) != 5:
#         print("Usage: python topsis.py <inputFile> <weights> <impacts> <outputFile>")
#         sys.exit(1)
# 
#     _, input_file, weights, impacts, output_file = sys.argv
#     topsis(input_file, weights, impacts, output_file)
# 
#

"""# **Running the program in command line style**"""

!python topsis.py /content/Topsis-Dataset.csv "1,1,1,1" "+,-,-,+" output.csv

"""# **Viewing of the output file**"""

import pandas as pd
pd.read_csv("output.csv")

"""##**Output Generated Successfully**

- TOPSIS algorithm executed correctly
- Output CSV file generated


"""